### ISSUE TITLE
The user is directed to the electron app after allowing authorization?

### ISSUE THREAD

**Issue by samhuang1111** [otiai10/electron-playground#2]
Hi!

If i don't use node.js module

How to write google oauth api js code and apply it to electron?

I use the example of google api document (node.js example code).

How to be redirected to the electron app after the user clicks on the permission authorization, and get the access token?

sorry my english is bad

**Comment by otiai10** [comment]
https://github.com/otiai10/electron-playground/blob/master/google-oauth-app/main.js#L37

**Comment by samhuang1111** [comment]
I want to ask you a question regain the token after the token expires?

access_token valid time 3600 seconds

I use "refresh_token" call oAuth2Client.getToken(refresh_token)

I get Error: invalid_grant

**Comment by otiai10** [comment]
Does the title of this issue describes your problem correctly? I'm confused now.
